module.exports = {
  FETCH_CHARACTERS_LIST: 'FETCH_CHARACTERS_LIST',
  FETCH_CHARACTERS_LIST_SUCCESS: 'FETCH_CHARACTERS_LIST_SUCCESS',
  FETCH_CHARACTERS_LIST_FAILURE: 'FETCH_CHARACTERS_LIST_FAILURE',
  SET_FILTERS: 'SET_FILTERS',
  SET_SELECTED_FILTERS: 'SET_SELECTED_FILTERS',
  SET_SORTING: 'SET_SORTING',
  SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
};
